### ISSUE TITLE
структура проекта

### ISSUE THREAD

**Issue by shevdi** [Zarwlar/Site_2#2]
Сейчас в папке pages лежат стили от страниц и миксины. Миксины тогда лучше вынести в отдельные блоки со своими собственными стилями. Сложить в отдельные папки

**Comment by Zarwlar** [comment]
Сделал, но не уверен в корректности решения

**Comment by shevdi** [comment]
У блоков прям свои названия. Не seller__stuff, а seller-stuff. Было бы неплохо так же как и блоки собрать в одной папке страницы. В каждой папке pug страницы со своими стилями, а в корневой оставить только страницу с ссылками на них.

**Comment by Zarwlar** [comment]
Окей, исправил
