### ISSUE TITLE
длинный текст не вмещается

### ISSUE THREAD

**Issue by shevdi** [Zarwlar/Site_2#5]
На странице seller длинный текст ломает верстку.

**Comment by Zarwlar** [comment]
Можно скриншот?)

**Comment by shevdi** [comment]
![seller](https://user-images.githubusercontent.com/14876842/27943297-082e690c-6308-11e7-8f07-5745c44900b3.png)

**Comment by shevdi** [comment]
И да, у меня знак рубля не отображается. Но если у тебя нормально, то не важно )

**Comment by Zarwlar** [comment]
Исправил, знак рубля у меня отображается)
