### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by shevdi** [Zarwlar/Site_2#6]
Местами совсем странные отступы. Например, в calendar.js. Если подключить eslint, то он выдаст ошибки )
Для css тоже есть линтеры, но именно под стилусом они не работают.

**Comment by Zarwlar** [comment]
Скорее всего, дело в том, что изначально у меня отступы были в виде табуляции) После прочтения стай-гайда произвёл автоматическую замену табуляции на 4 пробела, и судя по всему, где-то произошли косяки.
Накатил eslint, исправил)
